import type { IncentiveProgram } from '@/types';

// ─── Full Ontario Incentive Program Database (27+ programs) ─────────────────

export const INCENTIVE_PROGRAMS: IncentiveProgram[] = [
  // ─── IESO Programs ──────────────────────────────────────────────────────
  {
    id: 'ieso_custom',
    name: 'IESO Save on Energy — Retrofit (Custom)',
    provider: 'IESO',
    type: 'grant',
    description: 'Custom incentive based on measured/calculated energy savings. ~$0.20/kWh or $1,800/kW peak demand reduced, whichever is greater. Max 50% of eligible project costs.',
    region: ['ON'],
    sector: ['commercial', 'institutional', 'industrial'],
    ownershipTypes: ['private_corporation', 'reit', 'condo_corporation', 'municipality', 'university_college', 'hospital', 'school_board', 'non_profit', 'indigenous', 'pension_fund', 'other'],
    stacksWith: ['enbridge_custom', 'ct_itc', 'cib_private', 'cib_public', 'class_43_1'],
    excludes: ['ieso_epp'],
    reducesCtItcBase: true,
    preApprovalRequired: true,
    preApprovalTiming: 'BEFORE any purchase orders or work begins. Starting work early = PERMANENT disqualification.',
    paymentTiming: 'post_completion',
    applicationSequence: 1,
    isActive: true,
    lastVerified: '2026-03-01',
  },
  {
    id: 'ieso_prescriptive',
    name: 'IESO Save on Energy — Retrofit (Prescriptive)',
    provider: 'IESO',
    type: 'rebate',
    description: 'Product-specific rebates: LED fixtures $40-60/fixture, Solar PV $860/kW-AC (10kW-1MW). No M&V required.',
    region: ['ON'],
    sector: ['commercial', 'institutional', 'industrial'],
    ownershipTypes: ['private_corporation', 'reit', 'condo_corporation', 'municipality', 'university_college', 'hospital', 'school_board', 'non_profit', 'indigenous', 'pension_fund', 'other'],
    stacksWith: ['ieso_custom', 'enbridge_custom', 'ct_itc', 'cib_private'],
    excludes: ['ieso_instant_discounts'],
    reducesCtItcBase: true,
    preApprovalRequired: false,
    paymentTiming: 'post_completion',
    applicationSequence: 2,
    isActive: true,
    lastVerified: '2026-03-01',
  },
  {
    id: 'ieso_small_business',
    name: 'IESO Small Business Lighting',
    provider: 'IESO',
    type: 'grant',
    description: 'Free direct install: up to $3K lighting + $2.5K non-lighting. Co-delivery with Enbridge up to $26.5K.',
    region: ['ON'],
    sector: ['commercial'],
    ownershipTypes: ['private_corporation', 'other'],
    maxAmount: 26500,
    minElectricitykWh: 0,
    stacksWith: ['enbridge_custom'],
    excludes: ['ieso_custom'],
    reducesCtItcBase: false,
    preApprovalRequired: false,
    paymentTiming: 'upfront',
    applicationSequence: 1,
    isActive: true,
    lastVerified: '2026-03-01',
  },
  {
    id: 'ieso_instant_discounts',
    name: 'IESO Instant Discounts',
    provider: 'IESO',
    type: 'rebate',
    description: 'Point-of-sale LED discount $30-140/fixture. Zero paperwork.',
    region: ['ON'],
    sector: ['commercial', 'institutional', 'industrial'],
    ownershipTypes: ['private_corporation', 'reit', 'condo_corporation', 'municipality', 'university_college', 'hospital', 'school_board', 'non_profit', 'indigenous', 'pension_fund', 'other'],
    stacksWith: ['enbridge_custom', 'ct_itc'],
    excludes: ['ieso_prescriptive'],
    reducesCtItcBase: false,
    preApprovalRequired: false,
    paymentTiming: 'point_of_sale',
    applicationSequence: 0,
    isActive: true,
    lastVerified: '2026-03-01',
  },
  {
    id: 'ieso_demand_response',
    name: 'IESO Capacity Auction (Demand Response)',
    provider: 'IESO',
    type: 'performance',
    description: 'Recurring annual revenue ~$50/kW-year for curtailable load. Zero capex — pure upside post-commissioning.',
    region: ['ON'],
    sector: ['commercial', 'institutional', 'industrial'],
    ownershipTypes: ['private_corporation', 'reit', 'condo_corporation', 'municipality', 'university_college', 'hospital', 'school_board', 'non_profit', 'indigenous', 'pension_fund', 'other'],
    stacksWith: ['ieso_custom', 'enbridge_custom', 'ct_itc', 'cib_private'],
    excludes: [],
    reducesCtItcBase: false,
    preApprovalRequired: false,
    paymentTiming: 'ongoing',
    applicationSequence: 10,
    isActive: true,
    lastVerified: '2026-03-01',
  },

  // ─── Enbridge Programs ──────────────────────────────────────────────────
  {
    id: 'enbridge_custom',
    name: 'Enbridge Commercial Custom Retrofit',
    provider: 'Enbridge Gas',
    type: 'grant',
    description: 'Based on gas savings: $0.25/m³ first 400K m³, $0.10/m³ above. Max $100K commercial, $500K institutional.',
    region: ['ON'],
    sector: ['commercial', 'institutional'],
    ownershipTypes: ['private_corporation', 'reit', 'condo_corporation', 'municipality', 'university_college', 'hospital', 'school_board', 'non_profit', 'indigenous', 'pension_fund', 'other'],
    fuelTypes: ['gas'],
    stacksWith: ['ieso_custom', 'ieso_prescriptive', 'ct_itc', 'cib_private'],
    excludes: ['enbridge_p4p'],
    reducesCtItcBase: true,
    preApprovalRequired: true,
    preApprovalTiming: 'BEFORE any purchase orders or work begins.',
    paymentTiming: 'post_completion',
    applicationSequence: 1,
    isActive: true,
    lastVerified: '2026-03-01',
  },
  {
    id: 'enbridge_p4p',
    name: 'Enbridge Pay-for-Performance (P4P)',
    provider: 'Enbridge Gas',
    type: 'performance',
    description: 'Annual performance-based incentive. Free coaching + baseline. Target 20% gas savings over 3 years.',
    region: ['ON'],
    sector: ['commercial', 'institutional'],
    ownershipTypes: ['private_corporation', 'reit', 'condo_corporation', 'municipality', 'university_college', 'hospital', 'school_board', 'non_profit', 'indigenous', 'pension_fund', 'other'],
    fuelTypes: ['gas'],
    stacksWith: ['ieso_custom'],
    excludes: ['enbridge_custom'],
    reducesCtItcBase: false,
    preApprovalRequired: false,
    paymentTiming: 'ongoing',
    applicationSequence: 5,
    isActive: true,
    lastVerified: '2026-03-01',
  },

  // ─── Federal Programs ───────────────────────────────────────────────────
  {
    id: 'ct_itc',
    name: 'Clean Technology Investment Tax Credit (CT ITC)',
    provider: 'CRA / Federal',
    type: 'tax_credit',
    description: '30% refundable tax credit on ASHP, Solar PV, DHW heat pump. LED NOT eligible. Grants reduce basis first. Taxable corps only.',
    region: ['ON', 'QC', 'BC', 'AB', 'SK', 'MB', 'NS', 'NB', 'PE', 'NL'],
    sector: ['commercial', 'institutional', 'industrial'],
    ownershipTypes: ['private_corporation', 'reit'],
    stacksWith: ['ieso_custom', 'ieso_prescriptive', 'enbridge_custom', 'cib_private', 'class_43_1'],
    excludes: ['ce_itc'],
    reducesCtItcBase: false,
    preApprovalRequired: false,
    paymentTiming: 'tax_filing',
    applicationSequence: 8,
    isActive: true,
    lastVerified: '2026-03-01',
    expiryDate: '2034-12-31',
  },
  {
    id: 'ce_itc',
    name: 'Clean Electricity ITC (CE ITC)',
    provider: 'CRA / Federal',
    type: 'tax_credit',
    description: '15% refundable for non-taxable entities (municipalities, Indigenous, pensions). Awaiting Royal Assent.',
    region: ['ON', 'QC', 'BC', 'AB', 'SK', 'MB', 'NS', 'NB', 'PE', 'NL'],
    sector: ['institutional'],
    ownershipTypes: ['municipality', 'indigenous', 'pension_fund', 'non_profit'],
    stacksWith: ['ieso_custom', 'enbridge_custom', 'cib_public'],
    excludes: ['ct_itc'],
    reducesCtItcBase: false,
    preApprovalRequired: false,
    paymentTiming: 'tax_filing',
    applicationSequence: 8,
    isActive: false,
    intakeStatus: 'Awaiting Royal Assent — expected 2026',
    lastVerified: '2026-03-01',
  },
  {
    id: 'class_43_1',
    name: 'Accelerated CCA (Class 43.1)',
    provider: 'CRA / Federal',
    type: 'tax_credit',
    description: '30% declining balance CCA on clean energy equipment. Year-1 saving ~$10-15K on $380K ASHP.',
    region: ['ON', 'QC', 'BC', 'AB', 'SK', 'MB', 'NS', 'NB', 'PE', 'NL'],
    sector: ['commercial', 'industrial'],
    ownershipTypes: ['private_corporation', 'reit'],
    stacksWith: ['ieso_custom', 'enbridge_custom', 'ct_itc', 'cib_private'],
    excludes: [],
    reducesCtItcBase: false,
    preApprovalRequired: false,
    paymentTiming: 'tax_filing',
    applicationSequence: 9,
    isActive: true,
    lastVerified: '2026-03-01',
  },
  {
    id: 'cib_private',
    name: 'CIB Building Retrofits Initiative (Private)',
    provider: 'Canada Infrastructure Bank',
    type: 'financing',
    description: 'Sub-commercial rates (2.0-3.5%) via Scotiabank/BMO. Min 30% GHG reduction required. Up to 20-year term.',
    region: ['ON', 'QC', 'BC', 'AB', 'SK', 'MB', 'NS', 'NB', 'PE', 'NL'],
    sector: ['commercial'],
    ownershipTypes: ['private_corporation', 'reit', 'condo_corporation'],
    minGHGReduction: 0.30,
    stacksWith: ['ieso_custom', 'enbridge_custom', 'ct_itc', 'class_43_1'],
    excludes: ['cib_public'],
    reducesCtItcBase: false,
    preApprovalRequired: false,
    paymentTiming: 'upfront',
    applicationSequence: 3,
    isActive: true,
    lastVerified: '2026-03-01',
  },
  {
    id: 'cib_public',
    name: 'CIB Building Retrofits Initiative (Public)',
    provider: 'Canada Infrastructure Bank',
    type: 'financing',
    description: 'Direct to MUSH entities (municipalities, universities, schools, hospitals).',
    region: ['ON', 'QC', 'BC', 'AB', 'SK', 'MB', 'NS', 'NB', 'PE', 'NL'],
    sector: ['institutional'],
    ownershipTypes: ['municipality', 'university_college', 'hospital', 'school_board'],
    minGHGReduction: 0.30,
    stacksWith: ['ieso_custom', 'enbridge_custom', 'ce_itc'],
    excludes: ['cib_private'],
    reducesCtItcBase: false,
    preApprovalRequired: false,
    paymentTiming: 'upfront',
    applicationSequence: 3,
    isActive: true,
    lastVerified: '2026-03-01',
  },
  {
    id: 'bdc_green',
    name: 'BDC Certified Green Building Loan',
    provider: 'Business Development Bank of Canada',
    type: 'financing',
    description: '100% project costs, interest rate discount, interest-only first 36 months, up to 25yr. Must intend green certification.',
    region: ['ON', 'QC', 'BC', 'AB', 'SK', 'MB', 'NS', 'NB', 'PE', 'NL'],
    sector: ['commercial'],
    ownershipTypes: ['private_corporation', 'other'],
    requiredCertifications: ['BOMA BEST Silver', 'ENERGY STAR 75+', 'LEED Silver'],
    stacksWith: ['ieso_custom', 'enbridge_custom', 'ct_itc'],
    excludes: ['cib_private'],
    reducesCtItcBase: false,
    preApprovalRequired: false,
    paymentTiming: 'upfront',
    applicationSequence: 4,
    isActive: true,
    lastVerified: '2026-03-01',
  },
  {
    id: 'nrcan_iso50001',
    name: 'NRCan ISO 50001 Implementation Grant',
    provider: 'Natural Resources Canada',
    type: 'grant',
    description: 'Up to 60% costs, max $40K/building. Energy management system implementation.',
    region: ['ON', 'QC', 'BC', 'AB', 'SK', 'MB', 'NS', 'NB', 'PE', 'NL'],
    sector: ['commercial', 'institutional', 'industrial'],
    ownershipTypes: ['private_corporation', 'reit', 'municipality', 'university_college', 'hospital', 'school_board', 'non_profit', 'other'],
    maxAmount: 40000,
    coveragePct: 0.60,
    stacksWith: ['ieso_custom', 'enbridge_custom'],
    excludes: [],
    reducesCtItcBase: false,
    preApprovalRequired: false,
    paymentTiming: 'post_completion',
    applicationSequence: 5,
    isActive: true,
    lastVerified: '2026-03-01',
  },
  {
    id: 'efficiency_capital',
    name: 'Efficiency Capital (Turnkey ESA)',
    provider: 'Efficiency Capital',
    type: 'financing',
    description: 'Turnkey Energy Services Agreement: zero upfront, triple risk transfer (technical, performance, financial), off-balance sheet.',
    region: ['ON'],
    sector: ['commercial', 'institutional'],
    ownershipTypes: ['private_corporation', 'reit', 'condo_corporation', 'municipality', 'university_college', 'hospital', 'school_board', 'non_profit', 'other'],
    stacksWith: ['ieso_custom', 'enbridge_custom', 'ct_itc'],
    excludes: [],
    reducesCtItcBase: false,
    preApprovalRequired: false,
    paymentTiming: 'ongoing',
    applicationSequence: 4,
    isActive: true,
    lastVerified: '2026-03-01',
  },
  {
    id: 'cmhc_mli_select',
    name: 'CMHC MLI Select',
    provider: 'CMHC',
    type: 'financing',
    description: 'Up to 95% LTV, 50-year amortization. Climate points for deep retrofits. Multi-res/mixed-use.',
    region: ['ON', 'QC', 'BC', 'AB', 'SK', 'MB', 'NS', 'NB', 'PE', 'NL'],
    sector: ['residential'],
    ownershipTypes: ['private_corporation', 'reit', 'condo_corporation', 'non_profit'],
    stacksWith: ['ieso_custom', 'enbridge_custom', 'ct_itc'],
    excludes: [],
    reducesCtItcBase: false,
    preApprovalRequired: false,
    paymentTiming: 'upfront',
    applicationSequence: 4,
    isActive: true,
    lastVerified: '2026-03-01',
  },

  // ─── Municipal Programs ─────────────────────────────────────────────────
  {
    id: 'toronto_erl',
    name: 'Toronto Energy Retrofit Loan (ERL)',
    provider: 'City of Toronto',
    type: 'financing',
    description: 'Up to 100% project cost, 30yr, ~3.5-4.5%, unsecured, 1yr interest-free. Toronto buildings only.',
    region: ['ON'],
    sector: ['commercial', 'institutional'],
    ownershipTypes: ['private_corporation', 'reit', 'condo_corporation', 'non_profit', 'other'],
    jurisdictions: ['Toronto'],
    stacksWith: ['ieso_custom', 'enbridge_custom', 'ct_itc'],
    excludes: ['cib_private'],
    reducesCtItcBase: false,
    preApprovalRequired: false,
    paymentTiming: 'upfront',
    applicationSequence: 4,
    isActive: true,
    lastVerified: '2026-03-01',
  },
  {
    id: 'fcm_gmf',
    name: 'FCM Green Municipal Fund',
    provider: 'Federation of Canadian Municipalities',
    type: 'grant',
    description: 'Study: 50% max $65K-$200K. Capital: 15% grant + loan up to $10M. Municipalities and partners only.',
    region: ['ON', 'QC', 'BC', 'AB', 'SK', 'MB', 'NS', 'NB', 'PE', 'NL'],
    sector: ['institutional'],
    ownershipTypes: ['municipality'],
    maxAmount: 10000000,
    stacksWith: ['ieso_custom', 'enbridge_custom'],
    excludes: [],
    reducesCtItcBase: false,
    preApprovalRequired: false,
    paymentTiming: 'post_completion',
    applicationSequence: 3,
    isActive: true,
    lastVerified: '2026-03-01',
  },
];
