/**
 * Build-time script: reads surrogate_coefficients.json and generates
 * src/engine/surrogate/lowRiseOffice.ts with embedded coefficients.
 *
 * Run: npx tsx scripts/generateSurrogateConstants.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const INPUT = path.resolve(__dirname, '../surrogate_coefficients.json');
const OUTPUT = path.resolve(__dirname, '../src/engine/surrogate/lowRiseOffice.ts');

const data = JSON.parse(fs.readFileSync(INPUT, 'utf-8'));

function fmt(arr: number[]): string {
  return `[${arr.map(v => v.toString()).join(', ')}]`;
}

function fmtPowers(powers: number[][]): string {
  const lines = powers.map(p => `  [${p.join(', ')}],`);
  return `[\n${lines.join('\n')}\n]`;
}

let ts = `// ═══════════════════════════════════════════════════════════════════════════
// AUTO-GENERATED by scripts/generateSurrogateConstants.ts
// DO NOT EDIT MANUALLY — regenerate from surrogate_coefficients.json
//
// Archetype: ${data.metadata.archetype}
// Climate Zone: ${data.metadata.climate_zone}
// Weather: ${data.metadata.weather_file}
// Training: ${data.metadata.n_simulations} EnergyPlus simulations
// Base Model: ${data.metadata.base_model}
// Reference Floor Area: ${data.metadata.reference_floor_area_m2} m²
// ═══════════════════════════════════════════════════════════════════════════

export const REFERENCE_FLOOR_AREA_M2 = ${data.metadata.reference_floor_area_m2};

export const FEATURE_NAMES = ${JSON.stringify(data.feature_names)} as const;

export const FEATURE_RANGES: Record<string, { min: number; max: number; baseline: number }> = ${JSON.stringify(data.feature_ranges, null, 2).replace(/"desc":[^,}]+(,)?/g, '')};

// ─── Surrogate Input / Output Interfaces ────────────────────────────────────

export interface SurrogateInput {
  wall_rsi: number;
  roof_rsi: number;
  window_u: number;
  window_shgc: number;
  infiltration_ach: number;
  lpd: number;
  epd: number;
  heating_efficiency: number;
  ventilation_rate: number;
  hrv_effectiveness: number;
}

export interface SurrogateOutput {
  annual_elec_kWh: number;
  annual_gas_m3: number;
  cooling_kWh: number;
  lighting_kWh: number;
  equipment_kWh: number;
  fans_kWh: number;
  heating_gas_kWh: number;
  total_ekWh: number;
  total_EUI_ekWh_m2: number;
}

// ─── Model Coefficients ─────────────────────────────────────────────────────

`;

// Emit shared poly_powers (same for all degree-2 models with 10 features)
const firstModel = Object.values(data.models)[0] as any;
ts += `const POLY_POWERS: number[][] = ${fmtPowers(firstModel.poly_powers)};\n\n`;

// Emit per-model coefficients
const modelNames = Object.keys(data.models);
for (const name of modelNames) {
  const model = data.models[name];
  const NAME = name.toUpperCase();
  ts += `// ${name}: R² = ${model.r2.toFixed(6)}, CV R² = ${model.cv_r2_mean.toFixed(6)} ± ${model.cv_r2_std.toFixed(6)}\n`;
  ts += `const ${NAME}_COEFFICIENTS: number[] = ${fmt(model.coefficients)};\n`;
  ts += `const ${NAME}_SCALER_MEAN: number[] = ${fmt(model.scaler_mean)};\n`;
  ts += `const ${NAME}_SCALER_SCALE: number[] = ${fmt(model.scaler_scale)};\n`;
  if (model.y_min !== undefined) {
    ts += `const ${NAME}_Y_MIN = ${model.y_min};\n`;
    ts += `const ${NAME}_Y_MAX = ${model.y_max};\n`;
    ts += `const ${NAME}_Y_MEAN = ${model.y_mean};\n`;
  }
  ts += `\n`;
}

ts += `
// ─── Polynomial Evaluation ──────────────────────────────────────────────────

function standardize(values: number[], mean: number[], scale: number[]): number[] {
  return values.map((v, i) => (v - mean[i]) / scale[i]);
}

function evaluatePolynomial(
  xScaled: number[],
  coefficients: number[],
  powers: number[][]
): number {
  let result = 0;
  for (let t = 0; t < powers.length; t++) {
    let term = coefficients[t];
    for (let j = 0; j < powers[t].length; j++) {
      const p = powers[t][j];
      if (p === 1) {
        term *= xScaled[j];
      } else if (p === 2) {
        term *= xScaled[j] * xScaled[j];
      } else if (p > 2) {
        term *= Math.pow(xScaled[j], p);
      }
      // p === 0: multiply by 1 (no-op)
    }
    result += term;
  }
  return Math.max(0, result);
}

// ─── Input Clamping ─────────────────────────────────────────────────────────

export function clampInput(input: SurrogateInput): { clamped: SurrogateInput; warnings: string[] } {
  const warnings: string[] = [];
  const clamped = { ...input };

  for (const key of FEATURE_NAMES) {
    const range = FEATURE_RANGES[key];
    if (!range) continue;
    const val = clamped[key as keyof SurrogateInput];
    if (val < range.min) {
      warnings.push(\`\${key} clamped from \${val.toFixed(2)} to min \${range.min}\`);
      (clamped as Record<string, number>)[key] = range.min;
    } else if (val > range.max) {
      warnings.push(\`\${key} clamped from \${val.toFixed(2)} to max \${range.max}\`);
      (clamped as Record<string, number>)[key] = range.max;
    }
  }

  return { clamped, warnings };
}

// ─── Prediction Functions ───────────────────────────────────────────────────

function inputToArray(input: SurrogateInput): number[] {
  return [
    input.wall_rsi, input.roof_rsi, input.window_u, input.window_shgc,
    input.infiltration_ach, input.lpd, input.epd,
    input.heating_efficiency, input.ventilation_rate, input.hrv_effectiveness,
  ];
}

function predictTarget(
  values: number[],
  coefficients: number[],
  scalerMean: number[],
  scalerScale: number[]
): number {
  const scaled = standardize(values, scalerMean, scalerScale);
  return evaluatePolynomial(scaled, coefficients, POLY_POWERS);
}

export function predictEnergy(input: SurrogateInput): SurrogateOutput {
  const { clamped } = clampInput(input);
  const values = inputToArray(clamped);

  const annual_elec_kWh = predictTarget(values, ANNUAL_ELEC_KWH_COEFFICIENTS, ANNUAL_ELEC_KWH_SCALER_MEAN, ANNUAL_ELEC_KWH_SCALER_SCALE);
  const annual_gas_m3 = predictTarget(values, ANNUAL_GAS_M3_COEFFICIENTS, ANNUAL_GAS_M3_SCALER_MEAN, ANNUAL_GAS_M3_SCALER_SCALE);
  const cooling_kWh = predictTarget(values, COOLING_KWH_COEFFICIENTS, COOLING_KWH_SCALER_MEAN, COOLING_KWH_SCALER_SCALE);
  const lighting_kWh = predictTarget(values, LIGHTING_KWH_COEFFICIENTS, LIGHTING_KWH_SCALER_MEAN, LIGHTING_KWH_SCALER_SCALE);
  const equipment_kWh = predictTarget(values, EQUIPMENT_KWH_COEFFICIENTS, EQUIPMENT_KWH_SCALER_MEAN, EQUIPMENT_KWH_SCALER_SCALE);
  const fans_kWh = predictTarget(values, FANS_KWH_COEFFICIENTS, FANS_KWH_SCALER_MEAN, FANS_KWH_SCALER_SCALE);
  const heating_gas_kWh = predictTarget(values, HEATING_GAS_KWH_COEFFICIENTS, HEATING_GAS_KWH_SCALER_MEAN, HEATING_GAS_KWH_SCALER_SCALE);

  const gas_ekwh = annual_gas_m3 * 10.33;
  const total_ekWh = annual_elec_kWh + gas_ekwh;

  return {
    annual_elec_kWh: Math.round(annual_elec_kWh),
    annual_gas_m3: Math.round(annual_gas_m3),
    cooling_kWh: Math.round(cooling_kWh),
    lighting_kWh: Math.round(lighting_kWh),
    equipment_kWh: Math.round(equipment_kWh),
    fans_kWh: Math.round(fans_kWh),
    heating_gas_kWh: Math.round(heating_gas_kWh),
    total_ekWh: Math.round(total_ekWh),
    total_EUI_ekWh_m2: Math.round(total_ekWh / REFERENCE_FLOOR_AREA_M2),
  };
}

export function predictForBuilding(input: SurrogateInput, actualArea_m2: number): SurrogateOutput {
  const base = predictEnergy(input);
  const scale = actualArea_m2 / REFERENCE_FLOOR_AREA_M2;

  return {
    annual_elec_kWh: Math.round(base.annual_elec_kWh * scale),
    annual_gas_m3: Math.round(base.annual_gas_m3 * scale),
    cooling_kWh: Math.round(base.cooling_kWh * scale),
    lighting_kWh: Math.round(base.lighting_kWh * scale),
    equipment_kWh: Math.round(base.equipment_kWh * scale),
    fans_kWh: Math.round(base.fans_kWh * scale),
    heating_gas_kWh: Math.round(base.heating_gas_kWh * scale),
    total_ekWh: Math.round(base.total_ekWh * scale),
    total_EUI_ekWh_m2: base.total_EUI_ekWh_m2, // EUI doesn't scale
  };
}
`;

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, ts, 'utf-8');
console.log(`Generated ${OUTPUT}`);
console.log(`Models: ${modelNames.join(', ')}`);
console.log(`Coefficients per model: ${firstModel.coefficients.length}`);
console.log(`Features: ${data.feature_names.length}`);
